import React, { useEffect, useState } from 'react';
import './App.css';

const correctAnswers = {
  "name": "Admin",
  "guld": "Spanien",
  "sølv": "England",
  "bronze": ["Holland", "Frankrig"],
  "Tyskland - Skotland": 1,
  "Ungarn - Schweiz": 2,
  "Spanien - Kroatien": 1,
  "Italien - Albanien": 1,
  "Polen - Holland": 2,
  "Slovenien - Danmark": "x",
  "Serbien - England": 2,
  "Rumænien - Ukraine": 1,
  "Belgien - Slovakiet": 2,
  "Østrig - Frankrig": 2,
  "Tyrkiet - Georgien": 1,
  "Portugal - Tjekkiet": 1,
  "Kroatien - Albanien": "x",
  "Tyskland - Ungarn": 1,
  "Skotland - Schweiz": "x",
  "Slovenien - Serbien": "x",
  "Danmark - England": "x",
  "Spanien - Italien": 1,
  "Slovakiet - Ukraine": 2,
  "Polen - Østrig": 2,
  "Holland - Frankrig": "x",
  "Georgien - Tjekkiet": "x",
  "Tyrkiet - Portugal": 2,
  "Belgien - Rumænien": 1,
  "Schweiz - Tyskland": "x",
  "Skotland - Ungarn": 2,
  "Albanien - Spanien": 2,
  "Kroatien - Italien": "x",
  "Frankrig - Polen": "x",
  "Holland - Østrig": 2,
  "Danmark - Serbien": "x",
  "England - Slovenien": "x",
  "Slovakiet - Rumænien": "x",
  "Ukraine - Belgien": "x",
  "Georgien - Portugal": 1,
  "Tjekkiet - Tyrkiet": 2
};

const userAnswers = [
  {  "name": "Alexandar Kuburovic",  "guld": "Frankrig",  "sølv": "Spanien",  "bronze": "England",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": 1,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Anne Helmine Olesen",  "guld": "England",  "sølv": "Frankrig",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Danmark - England": 2,  "Spanien - Italien": 1,  "Holland - Frankrig": 1,  "Tyrkiet - Portugal": 2,  "Georgien - Tjekkiet": 2,  "Danmark - Serbien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 2,  "Kroatien - Italien": "x",  "Albanien - Spanien": 2,  "Slovenien - Serbien": 2,  "England - Slovenien": 1,  "Polen - Østrig": "x",  "Holland - Østrig": 1,  "Frankrig - Polen": 1,  "Ukraine - Belgien": 2,  "Slovakiet - Rumænien": "x",  "Belgien - Rumænien": 1,  "Slovakiet - Ukraine": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Lena Bardrum",  "guld": "Frankrig",  "sølv": "Tyskland",  "bronze": "Spanien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": 2,  "Slovakiet - Ukraine": "x",  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 1,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Frederik Dahl Pedersen",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Tyskland",  "Tyskland - Skotland": "x",  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 2,  "Holland - Frankrig": "x",  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": "x",  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": 1,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 2,  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Charlotte Breilev",  "guld": "Tyskland",  "sølv": "Portugal",  "bronze": "Danmark",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 1,  "Spanien - Kroatien": "x",  "Italien - Albanien": 1,  "Polen - Holland": "x",  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": "x",  "Skotland - Schweiz": 1,  "Slovenien - Serbien": "x",  "Danmark - England": "x",  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": "x",  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": "x",  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Jonas Fischer",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Emma Jensen, PU-MP",  "guld": "Frankrig",  "sølv": "Spanien",  "bronze": "Portugal",  "Tyskland - Skotland": "x",  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 1,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Christian B",  "guld": "England",  "sølv": "Holland",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": "x",  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": "x",  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": "x",  "Spanien - Italien": 2,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 1,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Danmark - Serbien": 1,  "Holland - Østrig": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Svend Oldenburg",  "guld": "England",  "sølv": "Frankrig",  "bronze": "Portugal",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 2,  "Italien - Albanien": 1,  "Polen - Holland": "x",  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 2,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Slovenien - Serbien": "x",  "Danmark - England": "x",  "Spanien - Italien": 2,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 1,  "Holland - Frankrig": 1,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 1,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 2,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 1,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Iben ",  "guld": "Frankrig",  "sølv": "Holland",  "bronze": "Italien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 2,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Slovenien - Serbien": 2,  "Danmark - England": 1,  "Spanien - Italien": 2,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Betina",  "guld": "Frankrig",  "sølv": "Spanien",  "bronze": "Italien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": 1,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": "x",  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Kent Sørensen",  "guld": "England",  "sølv": "Tyskland",  "bronze": "Frankrig",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": "x",  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": "x",  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Steffen Jørgensen",  "guld": "Holland",  "sølv": "Frankrig",  "bronze": "Kroatien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 1,  "Spanien - Kroatien": "x",  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": "x",  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": "x",  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": "x",  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 2,  "Holland - Frankrig": 1,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": 1,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Helle",  "guld": "Frankrig",  "sølv": "Tyskland",  "bronze": "Danmark",  "Tjekkiet - Tyrkiet": 2,  "Georgien - Portugal": 2,  "Ukraine - Belgien": 2,  "Slovakiet - Rumænien": 2,  "England - Slovenien": 1,  "Danmark - Serbien": 1,  "Holland - Østrig": 1,  "Frankrig - Polen": 1,  "Kroatien - Italien": 2,  "Albanien - Spanien": 2,  "Skotland - Ungarn": 2,  "Schweiz - Tyskland": 2,  "Belgien - Rumænien": 1,  "Tyrkiet - Portugal": 1,  "Georgien - Tjekkiet": 1,  "Holland - Frankrig": 1,  "Polen - Østrig": 2,  "Slovakiet - Ukraine": 2,  "Spanien - Italien": 2,  "Danmark - England": 2,  "Slovenien - Serbien": 1,  "Skotland - Schweiz": 1,  "Tyskland - Ungarn": 1,  "Kroatien - Albanien": 1,  "Portugal - Tjekkiet": 2,  "Tyrkiet - Georgien": 2,  "Østrig - Frankrig": 2,  "Belgien - Slovakiet": 2,  "Rumænien - Ukraine": 1,  "Serbien - England": 1,  "Slovenien - Danmark": 1,  "Polen - Holland": 1,  "Italien - Albanien": 2,  "Spanien - Kroatien": 2,  "Ungarn - Schweiz": 2,  "Tyskland - Skotland": 2},
  {  "name": "Hanne Guldager",  "guld": "Tyskland",  "sølv": "Danmark",  "bronze": "England",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 1,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 1,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": "x",  "Danmark - England": 1,  "Spanien - Italien": 2,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Rasmus Spangsberg Nielsen",  "guld": "England",  "sølv": "Frankrig",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": "x",  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": "x",  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": "x",  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x",  "Albanien - Spanien": 2},
  {  "name": "Henrik Traberg",  "guld": "Frankrig",  "sølv": "Belgien",  "bronze": "Portugal",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 2,  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 1,  "Skotland - Ungarn": 2,  "Albanien - Spanien": "x",  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Jeanette J Stengaard",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Italien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 2,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 1,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": 2,  "Danmark - England": 1,  "Spanien - Italien": 2,  "Slovakiet - Ukraine": "x",  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 1,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": 1,  "Frankrig - Polen": 1,  "Holland - Østrig": "x",  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 2,  "Ukraine - Belgien": "x",  "Georgien - Portugal": 1,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Michael Duerø",  "guld": "Tyskland",  "sølv": "Frankrig",  "bronze": "Spanien",  "Tyskland - Skotland": 1,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": "x",  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Belgien - Rumænien": 1,  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Frankrig - Polen": 1,  "Ungarn - Schweiz": "x",  "Tyrkiet - Portugal": 2,  "Schweiz - Tyskland": 2,  "Kroatien - Italien": 2,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Georgien - Portugal": 2,  "Ukraine - Belgien": 2,  "Slovakiet - Rumænien": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Johnny Fussing",  "guld": "Spanien",  "sølv": "Frankrig",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 1,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": "x",  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": "x",  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Kian H",  "guld": "Frankrig",  "sølv": "Tyskland",  "bronze": "England",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": "x",  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": 2,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Claus Mahler",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Spanien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 2,  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Solvej",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 2,  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Albanien - Spanien": 2,  "Skotland - Ungarn": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Mathias Alexander Kofoed",  "guld": "Frankrig",  "sølv": "Portugal",  "bronze": "England",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": "x",  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": "x",  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Trine Stangerup",  "guld": "Tyskland",  "sølv": "Danmark",  "bronze": "Frankrig",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": "x",  "Østrig - Frankrig": "x",  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": "x",  "Spanien - Italien": 2,  "Slovakiet - Ukraine": "x",  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": "x",  "Schweiz - Tyskland": "x",  "Albanien - Spanien": 2,  "Skotland - Ungarn": 1,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Jeanette Nielsen",  "guld": "Tyskland",  "sølv": "Holland",  "bronze": "Spanien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 1,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 2,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": 1,  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": "x",  "Polen - Østrig": 1,  "Holland - Frankrig": 1,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 1,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Kim Steen Hansen",  "guld": "Spanien",  "sølv": "Frankrig",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": "x",  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 1,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 2,  "Danmark - England": "x",  "Spanien - Italien": 1,  "Slovakiet - Ukraine": "x",  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": "x",  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Danmark - Serbien": 2,  "Holland - Østrig": "x",  "Frankrig - Polen": 1,  "Kroatien - Italien": "x",  "Albanien - Spanien": 2,  "Skotland - Ungarn": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Kåre Krebs Nissen",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": "x",  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": "x",  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": "x",  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": "x"},
  {  "name": "Ditte Enersen",  "guld": "Tyskland",  "sølv": "Italien",  "bronze": "Holland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 2,  "Italien - Albanien": 1,  "Polen - Holland": "x",  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Danmark - England": "x",  "Slovenien - Serbien": 2,  "Spanien - Italien": 2,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": 1,  "Georgien - Tjekkiet": "x",  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": "x",  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Jannie Høtoft",  "guld": "England",  "sølv": "Frankrig",  "bronze": "Spanien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 2,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": "x",  "Skotland - Ungarn": 2,  "Albanien - Spanien": 2,  "Kroatien - Italien": 1,  "Frankrig - Polen": "x",  "Holland - Østrig": 1,  "Danmark - Serbien": "x",  "England - Slovenien": 1,  "Slovakiet - Rumænien": 2,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Jeannette Almfort",  "guld": "England",  "sølv": "Frankrig",  "bronze": "Tyskland",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": "x",  "Serbien - England": 2,  "Rumænien - Ukraine": 1,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": "x",  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 2,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Rune", "guld": "England", "sølv": "Frankrig", "bronze": "Tyskland", "Tyskland - Skotland": 1, "Ungarn - Schweiz": 2, "Spanien - Kroatien": 1, "Italien - Albanien": 1, "Polen - Holland": 2, "Slovenien - Danmark": 2, "Serbien - England": 2, "Rumænien - Ukraine": 2, "Østrig - Frankrig": 2, "Belgien - Slovakiet": 1, "Tyrkiet - Georgien": 1, "Portugal - Tjekkiet": 1, "Kroatien - Albanien": 1, "Tyskland - Ungarn": 1, "Skotland - Schweiz": 2, "Slovenien - Serbien": 2, "Danmark - England": 2, "Spanien - Italien": 1, "Slovakiet - Ukraine": 2, "Polen - Østrig": 2, "Holland - Frankrig": 2, "Georgien - Tjekkiet": 2, "Tyrkiet - Portugal": 2, "Belgien - Rumænien": 2, "Albanien - Spanien": 2, "Kroatien - Italien": 2, "Frankrig - Polen": 1, "Holland - Østrig": 1, "Danmark - Serbien": 1, "Schweiz - Tyskland": 2, "Skotland - Ungarn": "x", "England - Slovenien": 1, "Slovakiet - Rumænien": "x", "Ukraine - Belgien": 2, "Georgien - Portugal": 2, "Tjekkiet - Tyrkiet": 1},
  {  "name": "Rikke Nissen",  "guld": "Frankrig",  "sølv": "England",  "bronze": "Danmark",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": 2,  "Italien - Albanien": 1,  "Polen - Holland": "x",  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": 1,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": "x",  "Portugal - Tjekkiet": 2,  "Kroatien - Albanien": "x",  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": "x",  "Slovenien - Serbien": 2,  "Danmark - England": "x",  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 2,  "Polen - Østrig": 1,  "Holland - Frankrig": "x",  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Tjekkiet - Tyrkiet": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": "x",  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 2,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2},
  {  "name": "Mette Bitsch Joanesarson",  "guld": "Tyskland",  "sølv": "Frankrig",  "bronze": "Kroatien",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Italien - Albanien": 1,  "Spanien - Kroatien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": "x",  "Serbien - England": 2,  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Portugal - Tjekkiet": 1,  "Tyrkiet - Georgien": "x",  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Slovenien - Serbien": 2,  "Danmark - England": 2,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": "x",  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": "x",  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1},
  {  "name": "Iben Rude",  "guld": "Tyskland",  "sølv": "Portugal",  "bronze": "Danmark",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": "x",  "Spanien - Kroatien": "x",  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": "x",  "Rumænien - Ukraine": 2,  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 2,  "Portugal - Tjekkiet": 1,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 1,  "Slovenien - Serbien": 1,  "Danmark - England": 1,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": 1,  "Georgien - Tjekkiet": 1,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": "x",  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": "x",  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": 2,  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 2},
  {  "name": "Danjal",  "guld": "Danmark",  "sølv": "Tyskland",  "bronze": "Frankrig",  "Tyskland - Skotland": 1,  "Ungarn - Schweiz": 2,  "Spanien - Kroatien": 1,  "Italien - Albanien": 1,  "Polen - Holland": 2,  "Slovenien - Danmark": 2,  "Serbien - England": 2,  "Rumænien - Ukraine": "x",  "Belgien - Slovakiet": 1,  "Østrig - Frankrig": 2,  "Tyrkiet - Georgien": 1,  "Portugal - Tjekkiet": 2,  "Kroatien - Albanien": 1,  "Tyskland - Ungarn": 1,  "Skotland - Schweiz": 2,  "Slovenien - Serbien": 1,  "Danmark - England": 1,  "Spanien - Italien": 1,  "Slovakiet - Ukraine": 1,  "Polen - Østrig": 1,  "Holland - Frankrig": 2,  "Georgien - Tjekkiet": 2,  "Tyrkiet - Portugal": 2,  "Belgien - Rumænien": 1,  "Schweiz - Tyskland": 2,  "Skotland - Ungarn": 1,  "Albanien - Spanien": 2,  "Kroatien - Italien": 2,  "Frankrig - Polen": 1,  "Holland - Østrig": 1,  "Danmark - Serbien": 1,  "England - Slovenien": 1,  "Slovakiet - Rumænien": "x",  "Ukraine - Belgien": 2,  "Georgien - Portugal": 2,  "Tjekkiet - Tyrkiet": 1}
];

function calculateScore(userAnswers, correctAnswers) {
  let score = 0;
  for (const key in correctAnswers) {
    const correctValue = correctAnswers[key];
    const userValue = userAnswers[key];
    
    if (key === "guld") {
      if (userValue === correctValue) {
        score += 3;
      }
    } else if (key === "sølv") {
      if (userValue === correctValue) {
        score += 2;
      }
    } else {
      if (Array.isArray(correctValue)) {
        if (correctValue.includes(userValue)) {
          score += 1;
        }
      } else {
        if (userValue === correctValue) {
          score += 1;
        }
      }
    }
  }

    // Additional points for guld, sølv, and bronze guesses in other medal categories
    const medals = ["guld", "sølv", "bronze"];
    medals.forEach((medal) => {
      const userValue = userAnswers[medal];
      medals.forEach((key) => {
        if (Array.isArray(correctAnswers[key])) {
          if (correctAnswers[key].includes(userValue)) {
            score += 1;
            return;
          }
        } else {
          if (userValue === correctAnswers[key]) {
            score += 1;
            return;
          }
        }
      });
    });
  return score;
}

function App() {
  const [scores, setScores] = useState([]);
  const [visibleTooltip, setVisibleTooltip] = useState(null);

  useEffect(() => {
    const newScores = userAnswers.map(user => ({
      name: user.name,
      score: calculateScore(user, correctAnswers),
      answers: user
    }));

    newScores.sort((a, b) => b.score - a.score);
    setScores(newScores);
  }, []);

  const toggleTooltip = (index) => {
    if (visibleTooltip === index) {
      setVisibleTooltip(null);
    } else {
      setVisibleTooltip(index);
    }
  };

  return (
    <div className="App">
      <h1>EM 2024 resultat</h1>
     
      <ul>
        {scores.map((user, index) => (
          <li key={index} className="user-item">
            <div className="tooltip-container">
              {index + 1}. <span className="user-name" onClick={() => toggleTooltip(index)}>{user.name}</span>: {user.score}
              {visibleTooltip === index && (
                <div className="tooltip">
                  {Object.entries(user.answers).map(([question, answer], i) => (
                    question !== "name" && <div key={i}><strong>{question}</strong>: {answer}</div>
                  ))}
                </div>
              )}
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;