"name": "Admin",
"guld": "Albanien",
"sølv": "Belgien",
"bronze": ["Danmark", "Tyskland"],
"Tyskland - Skotland": "x",
"Ungarn - Schweiz": "x",
"Spanien - Kroatien": "x",
"Italien - Albanien": "x",
"Polen - Holland": "x",
"Slovenien - Danmark": "x",
"Serbien - England": "x",
"Rumænien - Ukraine": "x",
"Belgien - Slovakiet": "x",
"Østrig - Frankrig": "x",
"Tyrkiet - Georgien": "x",
"Portugal - Tjekkiet": "x",
"Kroatien - Albanien": "x",
"Tyskland - Ungarn": "x",
"Skotland - Schweiz": "x",
"Slovenien - Serbien": "x",
"Danmark - England": "x",
"Spanien - Italien": "x",
"Slovakiet - Ukraine": "x",
"Polen - Østrig": "x",
"Holland - Frankrig": "x",
"Georgien - Tjekkiet": "x",
"Tyrkiet - Portugal": "x",
"Belgien - Rumænien": "x",
"Schweiz - Tyskland": "x",
"Skotland - Ungarn": "x",
"Albanien - Spanien": "x",
"Kroatien - Italien": "x",
"Frankrig - Polen": "x",
"Holland - Østrig": "x",
"Danmark - Serbien": "x",
"England - Slovenien": "x",
"Slovakiet - Rumænien": "x",
"Ukraine - Belgien": "x",
"Georgien - Portugal": "x",
"Tjekkiet - Tyrkiet": "x"