{
"name": "Jonas",
"guld": "Sverige",
"sølv": "Tyskland",
"bronze": "Slovakiet",
"Tyskland - Skotland": 1,
"Ungarn - Schweiz": 1,
"Spanien - Kroatien": 1,
"Italien - Albanien": "x",
"Polen - Holland": "x",
"Slovenien - Danmark": "x",
"Serbien - England": 2,
"Rumænien - Ukraine": 2,
"Belgien - Slovakiet": 2,
"Østrig - Frankrig": 1,
"Tyrkiet - Georgien": 1,
"Portugal - Tjekkiet": 1,
"Kroatien - Albanien": 1,
"Tyskland - Ungarn": 1,
"Skotland - Schweiz": 1,
"Slovenien - Serbien": 1,
"Danmark - England": 1,
"Spanien - Italien": 1,
"Slovakiet - Ukraine": 1,
"Polen - Østrig": 1,
"Holland - Frankrig": 1,
"Tyrkiet - Portugal": 1,
"Georgien - Tjekkiet": 1,
"Belgien - Rumænien": 1,
"Schweiz - Tyskland": 1,
"Skotland - Ungarn": 1,
"Albanien - Spanien": 1,
"Kroatien - Italien": 1,
"Frankrig - Polen": 1,
"Holland - Østrig": 1,
"Danmark - Serbien": 1,
"England - Slovenien": 1,
"Slovakiet - Rumænien": 1,
"Ukraine - Belgien": 1,
"Georgien - Portugal": 1,
"Tjekkiet - Tyrkiet": 1
},
{
"name": "Hans",
"guld": "Polen",
"sølv": "Portugal",
"bronze": "England",
"Tyskland - Skotland": "x",
"Ungarn - Schweiz": "x",
"Spanien - Kroatien": 2,
"Italien - Albanien": 1,
"Polen - Holland": 2,
"Serbien - England": 1,
"Slovenien - Danmark": 2,
"Rumænien - Ukraine": "x",
"Belgien - Slovakiet": 2,
"Østrig - Frankrig": 2,
"Tyrkiet - Georgien": "x",
"Portugal - Tjekkiet": 1,
"Kroatien - Albanien": "x",
"Tyskland - Ungarn": 2,
"Skotland - Schweiz": "x",
"Slovenien - Serbien": "x",
"Danmark - England": 1,
"Spanien - Italien": "x",
"Slovakiet - Ukraine": 2,
"Polen - Østrig": "x",
"Holland - Frankrig": 1,
"Georgien - Tjekkiet": "x",
"Tyrkiet - Portugal": 2,
"Belgien - Rumænien": "x",
"Schweiz - Tyskland": 1,
"Skotland - Ungarn": "x",
"Albanien - Spanien": 2,
"Kroatien - Italien": "x",
"Frankrig - Polen": 1,
"Holland - Østrig": 1,
"Danmark - Serbien": "x",
"England - Slovenien": 2,
"Slovakiet - Rumænien": "x",
"Ukraine - Belgien": "x",
"Georgien - Portugal": "x",
"Tjekkiet - Tyrkiet": 1
},
{
"name": "Morten",
"guld": "Ukraine",
"sølv": "Ungarn",
"bronze": "Østrig",
"Tyskland - Skotland": 2,
"Ungarn - Schweiz": 2,
"Spanien - Kroatien": 2,
"Italien - Albanien": 2,
"Polen - Holland": 2,
"Slovenien - Danmark": 2,
"Serbien - England": 2,
"Rumænien - Ukraine": 2,
"Belgien - Slovakiet": 2,
"Østrig - Frankrig": 2,
"Tyrkiet - Georgien": 2,
"Portugal - Tjekkiet": 2,
"Kroatien - Albanien": 2,
"Tyskland - Ungarn": "x",
"Skotland - Schweiz": "x",
"Slovenien - Serbien": "x",
"Danmark - England": "x",
"Spanien - Italien": 1,
"Slovakiet - Ukraine": 1,
"Polen - Østrig": 1,
"Holland - Frankrig": 1,
"Georgien - Tjekkiet": 1,
"Tyrkiet - Portugal": "x",
"Belgien - Rumænien": "x",
"Schweiz - Tyskland": 1,
"Skotland - Ungarn": "x",
"Albanien - Spanien": 2,
"Kroatien - Italien": 1,
"Frankrig - Polen": "x",
"Holland - Østrig": 2,
"Danmark - Serbien": "x",
"England - Slovenien": 1,
"Slovakiet - Rumænien": "x",
"Ukraine - Belgien": 2,
"Georgien - Portugal": "x",
"Tjekkiet - Tyrkiet": 1
}